services:
  - docker

before_install:
  - docker build -t rev01ver/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run rev01ver/react-test npm test -- --coverage

after_success:
  - docker build -t crank777/multi-client ./client
  - docker build -t crank777/multi-nginx ./nginx
  - docker build -t crank777/multi-server ./server
  - docker build -t crank777/multi-worker ./worker

#login in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 

#Take those images and push them to docker hub - docker cred!
  - docker push crank777/multi-client
  - docker push crank777/multi-nginx
  - docker push crank777/multi-server
  - docker push crank777/multi-worker
 


